name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew build
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

  #     - name: Run snapshot action
  #       uses: mikepenz/gradle-dependency-submission@v0.8.6
  #       with:
  #         gradle-build-module: |-
  #           :app
  # review:
  #   if: github.event_name == 'pull_request'
  #   needs: sbom
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: write
  #   steps:
  #     - name: 'Checkout Repository'
  #       uses: actions/checkout@v3
  #     - name: 'Dependency Review'
  #       uses: actions/dependency-review-action@v3
  #       with:
  #         comment-summary-in-pr: true
