name: Run Gradle Build

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle Build Action
        uses: gradle/gradle-build-action@v3
        with:
          dependency-graph: generate-and-upload
          cache-disabled: true
          
      - name: Build and test with Gradle
        run: ./gradlew build
        continue-on-error: true


  review:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      needs: build
      
      steps:
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4



